export const UI_TEXT = {
  selectLocationTitle: "Select location",
  jobTypeTitle: "Job Type",
  jobCategoryTitle: "Job Category",
  experienceTitle: "Experience",
  salaryTitle: "Salary",
  educationTitle: "Education",
  jobLevelTitle: "Job Level",
  findJobsTitle: "Find jobs",
  homeTitle: "Home",
  selectCategoryTitle: "Select Category",
  filterTitle: "Filter",
  clearAllFilter: "Clear all filter",
  applyNowTitle: "Apply Now",
  alreadyAppliedTitle: "Already Applied",
  jobExpired: "Job Expired",
  daysRemainingTitle: "Days Remaining",
  candidateProfileSettingsTitle: "Candidate Profile Settings",
  proccesing: "Processing...",
  saveProfile: "Save Profile",
  employerProfileSettingsTitle: "Employer Profile Settings",
  postAJob: "Post A Job",
  editAJob: "Edit A Job",
  postJob: "Post Job",
  editJob: "Edit Job",
  scheduleMeeting: "Schedule Meeting",
  scheduledMeetings: "Scheduled Meetings",
  editMeeting: "Edit Meeting",
  selectDate: "Select Date",
  selectTime: "Select Time",
  Cancel: "Cancel",
  Schedule: "Schedule",
  jobDescription: "Job Description",
  notAuthorizedToPerform: "You are not authorized to perform this action.",
  myJobs: "My Jobs",
  jobDetailsTitle: "Job Details",
  jobDescriptionTitle: "Job Description",
  biography: "BIOGRAPHY",
  downloadResume: "Download My Resume",
  contactInformation: "Contact Information",
  emailAddress: "EMAIL ADDRESS",
  phone: "PHONE",
  location: "LOCATION",
  coverLetter: "COVER LETTER",
  jobOverviewTitle: "Job Overview",
  jobPostedTitle: "Job Posted:",
  educationDetailsTitle: "Education:",
  locationTitle: "Location",
  foundedInTitle: "Founded in",
  organizationTypeTitle: "Organization type",
  companySizeTitle: "Company size",
  phoneTitle: "Phone",
  emailTitle: "Email",
  websiteTitle: "Website",
  nationality: "Notionality",
  experience: "Experience",
  educations: "Educations",
  sendMail: "Send Mail",
  hireCandidates: "Hire Candidates",
};
